# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, ci, api/** ]
  pull_request:
    branches: [ master, dev ]

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    env:
      api_dir: ./api
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      
      # - name: Install pkgs
      #   run: go get -u ./...
      #   working-directory: ${{ env.api_dir }}

      - name: Build go API
        run: go build
        working-directory: ${{ env.api_dir }}
      
      - name: Run tests API
        run: go test -cover ./... -v
        working-directory: ${{ env.api_dir }}
